### ISSUE TITLE
Remove trend line glow

### ISSUE THREAD

**Issue by cohenu** [nagix/chartjs-plugin-style#6]
Hey :)

I've added the following to my chart:
```js
outerGlowWidth: 10,
outerGlowColor: 'rgba(102, 85, 32, 1)',
```

and it seems like I have also hidden trend line drawn on my chart since the glow has been added to this line too and make it visible. is there any way to remove it ? 

Thank you, merry christmas and happy new year!

**Comment by nagix** [comment]
Are you showing the trend line as a separate dataset from the main lines/bars? In that case, you can just set `outerGlowWidth` to `0` or `outerGlowColor` to `'transparent'` for the trend line dataset.

**Comment by cohenu** [comment]
No, actually I have only one dataset (line chart), and once I activate the glow it seems like I have another transparent line but I cannot find from where this trend line coming from.

**Comment by nagix** [comment]
Can you share JSFiddle, Codepen or screenshot?

**Comment by cohenu** [comment]
link for screenshot: https://i.imgur.com/sNweRB5.jpg

**Comment by nagix** [comment]
This is clearly a bug in the outer glow function in line charts. I will fix it shortly.

**Comment by cohenu** [comment]
Thank you nagix very appreciated!

**Comment by nagix** [comment]
This issue has been fixed in 6b99442.

**Comment by cohenu** [comment]
Hi nagix :) thank you for the fix!
I've just tested it and still have the same issue, see picture: https://i.imgur.com/EK3tLuX.png (using version 0.3.2)

**Comment by nagix** [comment]
Did you build a js file from the master branch? The fix is not merged into the release branch yet and will be included in v0.3.3 or v0.4.0 release.

**Comment by cohenu** [comment]
No I didn't, Sorry I didn't know. THANKS AGAIN! :)

**Comment by nagix** [comment]
Closing as v0.4.0 was just released.
